AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    Environment:
      Description: "Another Simple String Parameter With A List Of Allowed Values"
      Type: String
      Default: "dev"
      AllowedValues:
        - dev
        - qa
        - beta
        - prod
      ConstraintDescription: "Use valid environment values (dev, qa, beta, prod)"
    
Mappings:
      QuantitiOfInstances:
        dev:
          qty: 1
        qa:
          qty: 1
        beta:
          qty: 2
        prod:
          qty: 5

Resources:
    DemoResource:
      Type: "AWS::S3::Bucket"
      Properties:
        Tags:
          - Key: "InstanceQuantity"
            Value: !FindInMap [QuantitiOfInstances, !Ref Environment, qty]